#!/bin/sh -e

export CARGO_PROFILE_RELEASE_LTO="true"

cargo fetch --locked

cargo build --frozen --release --manifest-path crates/rust-analyzer/Cargo.toml

mkdir -p "$1/usr/bin"
cp target/release/rust-analyzer "$1/usr/bin/"
