#!/bin/sh

export DESTDIR="$1"

meson setup \
    -Dsysconfdir=/etc \
    -Dlocalstatedir=/var \
    -Duser_session=true \
    -Dprefix=/usr \
    -Dx11_autolaunch=disabled \
    -Dsystem_socket=/run/dbus/system_socket \
    -Ddoxygen_docs=disabled \
    -Dsystem_pid_file=/run/dbus/pid \
    -Dsystemd=disabled \
    build

ninja -C build
ninja -C build install

# Currently running s6, no need for this
# Install service.
#install -Dm755 dbus.run "$1/etc/sv/dbus/run"
#ln -s /run/runit/supervise.dbus "$1/etc/sv/dbus/supervise"
