#!/bin/sh

# install messagebus user
if ! $(id messagebus &> /dev/null); then
  echo "adding messagebus user"
  adduser messagebus -S -D -H -g 'System message bus' -h '/var/run/dbus'
fi
# TODO: adduser 
# useradd -c 'System message bus' -u 81 -s /sbin/nologin -r -d '/' dbus 2> /dev/null
