#!/bin/sh

if ! getent group messagebus >/dev/null 2>&1; then
  echo "adding messagebus group"
  addgroup -S messagebus
fi

if ! getent passwd messagebus >/dev/null 2>&1; then
  echo "adding messagebus user"
  adduser messagebus -S -D -H -G messagebus -g 'System message bus' -h '/run/dbus'
fi
