#!/bin/sh -e

meson \
    --prefix=/usr \
    -Dalsa=enabled \
    -Dlibmpv=true \
    -Dwayland=enabled \
    -Dx11=disabled \
    -Dlua=enabled \
    . output

ninja -C output
ninja -C output install

rm -rf \
    "$1/usr/share/zsh" \
    "$1/usr/share/bash-completion"
