#!/bin/sh -e
./configure \
    --prefix=/usr \
    --exec-prefix=/usr \
    --disable-systemd \
    --enable-library \
    --disable-obex \
    --mandir=/usr/share/man \
    --disable-cups \
    --with-udevdir=/dev

make
make DESTDIR="$1" install

# add service for bluetoothd
install -Dm775 bluetoothd.run "$1/etc/sv/bluetoothd/run"
ln -sf /run/runit/supervise.bluetoothd "$1/etc/sv/bluetoothd/supervise"
