#!/bin/sh -e

mkdir -p "$1/usr/lib/firmware/radeon"
cp radeon/PALM_me.bin "$1/usr/lib/firmware/radeon/"
cp radeon/PALM_pfp.bin "$1/usr/lib/firmware/radeon/"
cp radeon/SUMO_rlc.bin "$1/usr/lib/firmware/radeon/"
cp radeon/SUMO_uvd.bin "$1/usr/lib/firmware/radeon/"

mkdir -p "$1/usr/lib/firmware/rtl_nic"
cp rtl_nic/rtl8168e-3.fw "$1/usr/lib/firmware/rtl_nic/"

cp ath3k-1.fw "$1/usr/lib/firmware/"
