#!/bin/sh -e

[ -f /proc/config.gz ] || (echo "CONFIG_IKCONFIG and CONFIG_IKCONFIG_PROC must be enabled in kernel" && exit 1)

echo "Copying and decompressing current configuration"
cp /proc/config.gz .
gzip -d config.gz
mv config .config

echo "Moving lemon font to lib/fonts/"
mv font_lemon.c lib/fonts/

echo "Patching support for lemon font"
for patch in *.patch; do
    patch -p1 < "$patch"
done

echo "Running make olddefconfig with current configuration as base"
make olddefconfig
echo "fix"
sleep 2m
echo "Building source"
make

echo "Running make install"
mkdir "$1/boot"
INSTALL_PATH="$1/boot" make install
mv "$1/boot/vmlinuz" "$1/boot/vmlinuz-$2"
mv "$1/boot/System.map" "$1/boot/System.map-$2"
