#!/bin/sh -e

[ -f /proc/config.gz ] || (echo "CONFIG_IKCONFIG and CONFIG_IKCONFIG_PROC must be enabled in kernel" && exit 1)

echo "Copying and decompressing current configuration"
cp /proc/config.gz .
gzip -d config.gz
mv config .config

echo "Fix your config, you have 5 minutes"
sleep 1m

for i in 4 3 2 1; do
    echo "$i minute$([ $i -ne 1 ] && echo 's') remaining"
    sleep 1m
done

echo "Resuming build in 10s"
sleep 5

for i in 5 4 3 2 1; do
    echo $i
    sleep 1
done

echo "Moving lemon font to lib/fonts/"
mv font_lemon.c lib/fonts/

echo "Patching support for lemon font"
for patch in *.patch; do
    patch -p1 < "$patch"
done

echo "Running make olddefconfig with current configuration as base"
make olddefconfig

echo "Building source"
make

echo "Running make install"
mkdir "$1/boot"
INSTALL_PATH="$1/boot" make install
mv "$1/boot/vmlinuz" "$1/boot/vmlinuz-$2"
mv "$1/boot/System.map" "$1/boot/System.map-$2"
