#!/bin/sh -e

echo "Updating EFI"

# get vmlinuz name with version number from the installed manifest
kernel=$(basename $(grep vmlinuz $(dirname $0)/manifest))

# check if already mounted
mounted=$(mount | grep efivarfs > /dev/null; echo $?)

if [ "${mounted}" -ne 0 ]; then
  echo "Mounting efivarfs..."
  mount -t efivarfs none /sys/firmware/efi/efivars
fi

efibootmgr -B -L "KISS" -q
efibootmgr -c -L "KISS" -d /dev/sda -p 1 -l "\\$kernel" -u 'root=/dev/sda2 quiet' -q

if [ "$mounted" -ne 0 ]; then
  echo "Unmounting efivarfs..."
  umount /sys/firmware/efi/efivars
fi
